### ISSUE TITLE
AttributeError: Unknown property axisbg

### ISSUE THREAD

**Issue by sugeknowles** [paulbrodersen/matplotlib_venn_wordcloud#3]
I installed all the prerequisites on python3.6 and am getting the following error when trying to use the library.

matplotlib versions:

root@thehost:~# pip3 freeze | grep mat
matplotlib==2.2.2
matplotlib-venn==0.11.5
matplotlib-venn-wordcloud==0.2.1

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-3763343f67c3> in <module>()
     21 
     22 # create visualisation
---> 23 venn2_wordcloud(sets)

/usr/local/lib/python3.6/dist-packages/matplotlib_venn_wordcloud/_main.py in venn2_wordcloud(sets, set_labels, set_colors, set_edgecolors, alpha, ax, word_to_frequency, wordcloud_kwargs)
    186     venn.get_words_by_id = _func
    187 
--> 188     return _venn_wordcloud(venn, ax, word_to_frequency, **wordcloud_kwargs)
    189 
    190 

/usr/local/lib/python3.6/dist-packages/matplotlib_venn_wordcloud/_main.py in _venn_wordcloud(ExtendedVennDiagram, ax, word_to_frequency, **wordcloud_kwargs)
    372         img.rgba += wc.to_array() / 255.
    373 
--> 374     img.imshow(interpolation='bilinear')
    375 
    376     return ExtendedVennDiagram

/usr/local/lib/python3.6/dist-packages/matplotlib_venn_wordcloud/_main.py in imshow(self, **imshow_kwargs)
    435         bbox = self.ax.get_position() # in figure coordinates
    436         fig = self.ax.get_figure()
--> 437         subax = fig.add_axes(bbox, axisbg=None)
    438 
    439         # plot image

/usr/local/lib/python3.6/dist-packages/matplotlib/figure.py in add_axes(self, *args, **kwargs)
   1134 
   1135             # create the new axes using the axes class given
-> 1136             a = projection_class(self, rect, **kwargs)
   1137 
   1138         self._axstack.add(key, a)

/usr/local/lib/python3.6/dist-packages/matplotlib/axes/_base.py in __init__(self, fig, rect, facecolor, frameon, sharex, sharey, label, xscale, yscale, **kwargs)
    537 
    538         if len(kwargs):
--> 539             self.update(kwargs)
    540 
    541         if self.xaxis is not None:

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in update(self, props)
    886         try:
    887             ret = [_update_property(self, k, v)
--> 888                    for k, v in props.items()]
    889         finally:
    890             self.eventson = store

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in <listcomp>(.0)
    886         try:
    887             ret = [_update_property(self, k, v)
--> 888                    for k, v in props.items()]
    889         finally:
    890             self.eventson = store

/usr/local/lib/python3.6/dist-packages/matplotlib/artist.py in _update_property(self, k, v)
    879                 func = getattr(self, 'set_' + k, None)
    880                 if not callable(func):
--> 881                     raise AttributeError('Unknown property %s' % k)
    882                 return func(v)
    883 

AttributeError: Unknown property axisbg

**Comment by sugeknowles** [comment]
Fixed buy removing kwarg from main.py for axisbg.  It's been depricated in matplotlib 2.0+
https://matplotlib.org/api/api_changes.html

**Comment by paulbrodersen** [comment]
Sorry for the non-responsiveness (was in bed with the flu) and thanks for the heads-up. Will fix asap.
