### ISSUE TITLE
How to export higher resolution figure?

### ISSUE THREAD

**Issue by yzpan1** [paulbrodersen/matplotlib_venn_wordcloud#8]
This is a great representation of venn diagram analysis! I'm trying to generate a venn diagram with gene names in corresponding sets. The plot I saved in Spyder is tiny and blurry, how can I adjust the size of the plot and/or its resolution?

**Comment by paulbrodersen** [comment]
The figures are just matplotlib figures, so you can adjust the resolution using standard matplotlib syntax. 
For example:

```python
...
fig, ax = plt.subplots()
venn2_wordcloud([set1, set2], ax=ax)
fig.savefig("/path/to/figure.png", dpi=500) 
```

Personally, I save figures as vector graphics (SVG, PDF) and then the resolution is always adjusted to your current view.

```python
fig.savefig("/path/to/figure.pdf") 
```

**Comment by paulbrodersen** [comment]
There are also some spyder-specific settings you may want to look at if you don't want to export the figures:
https://stackoverflow.com/a/47166703/2912349

**Comment by paulbrodersen** [comment]
I will close this issue for now but feel free to re-open if neither of these suggestions resolves your problem.

**Comment by yzpan1** [comment]
Thank you Paul, I solved it! Appreciate it!
