### ISSUE TITLE
module 'numpy' has no attribute 'float' - numpy.float deprec as of numpy 1.24

### ISSUE THREAD

**Issue by GuiHue** [paulbrodersen/matplotlib_venn_wordcloud#9]
Execution of example will break when using recent versions of numpy, namely >= 1.24.

Fix illustrated here:
https://numpy.org/doc/stable/release/1.20.0-notes.html#deprecations

**Comment by GuiHue** [comment]
See PulLRequest

**Comment by paulbrodersen** [comment]
Merged pull request. Much obliged.
